### ISSUE TITLE
[Thinker 3.1] Alt+T menu not appearing.

### ISSUE THREAD

**Issue by JoshuaSFryer** [induktio/thinker#42]
I've freshly installed the Thinker 3.1 mod to a GOG installation on Windows 10, and when checking the version with Ctrl+F4 it correctly displays the version number when launched from `thinker.exe`. However, the mod's menu does not appear when pressing Alt+T; instead, it cycles through the terrain display modes (as if simply pressing T). Any assistance would be appreciated.

**Comment by joe86000** [comment]
Bump. Same issue here except I'm on Windows 11.

**Comment by JoshuaSFryer** [comment]
As a small update, I made a clean reinstall and installed PRACX (which I had not installed when reporting this issue), and no other mods; the PRACX ALT-R and ALT-T commands run without issue, so it doesn't seem to be an issue of another application or the OS hooking the key combination.

**Comment by joe86000** [comment]
Been doing some experimenting and here's what I can reproduce:
1. Clean install
2. Copy Thinker 3.1 files to game dir
3. Run Crossfire using Thinker.exe > Game runs in 4:3 and low res; Alt-T doesn't work. Edge scrolling and zoom (Z and X) are janky.
4. Copy **exactly the same** Thinker 3.1 files to game dir again
5. Run Crossfire using Thinker.exe again > Game now runs in 16:9 and hi-res; Alt-T works. Edge scrolling and zoom (Z and X) are still janky.
6. Install PRACX (1.11)
7. Run Crossfire using Thinker.exe again > Edge scrolling and zoom (Z and X) are smooth now. Mouse wheel zooming works. Alt-T does what it's supposed to in PRACX. No access to Thinker options.
8. Copy **only alphax.txt** file from Thinker 3.1 into game dir
9. Run Crossfire using Thinker.exe again > Edge scrolling and zoom (Z and X) are still smooth. Mouse wheel zooming doesn't work; mouse wheel moves unit instead. Alt-T displays Thinker options.

This seems like an acceptable compromise but I haven't played for more than a couple of minutes so I don't know what other issues might crop up down the road using this improvised setup.

**Comment by induktio** [comment]
I did some tests with Thinker 3.1 on Windows 10 as reported on [the other issue](https://github.com/induktio/thinker/issues/38) and didn't notice the problem described here. At least during the test ALT+T and CTRL+F4 were functioning properly, so I was not able to replicate the issue. Any follow up discussion should probably be directed to the other issue since these things might be related.

**Comment by xnaquada** [comment]
I'm having the exact same issue as identified in this and the other thread. 

Fresh install from GOG. Install Thinker 3.1. Sometimes loads fullscreen, sometimes its some odd 4:3 ratio (looks like 1024x768). What's more is that the ALT+T menu never worked once in game (neither custom start or quick start) Easy steps for me to reproduce are quick start, planetfall, confirm base HQ, scout is blinking read for action. From this point, no mod menu appears when entering the ALT+T keystroke. Actually it appears that keystroke is hide/toggling layers on the map (e.g. just shows geography, no units or base). Again, certainly no ALT+T mod menu loads , CTRL+F4 shows a mod menu that just displays the thinker version.

However in your other post @induktio , you provided the "old launcher" the modded terranx_mod.exe. I placed this in the directory and ran it directly and suddenly things worked fine. Also for the first time ever, I see the ALT-T menu in game (neat!).

So there's definitely something up. I can appreciate you going the lengths to reproduce with a VM on Win10 21H2 and not finding the issue, but as someone who is also on W10 21H2 (v.19044.2006) to update on patches, and a clean install of game from GoG-galaxy, and then install of Thinker 3.1 -- there is definitely something not quite right.

**Comment by xnaquada** [comment]
I'm having the exact same issue as identified in this and the other thread.

Fresh install from GOG. Install Thinker 3.1. Sometimes loads fullscreen+full resolution (for me 16:9/QHD), sometimes the game launches in some odd 4:3 ratio (looks like 1024x768). What's more is that the ALT+T menu never worked once in game (neither custom start or quick start). Easy steps for me to reproduce are quick start, planetfall, confirm base HQ, scout is blinking read for action. From this point, no mod menu appears when entering the ALT+T keystroke. Actually it appears that keystroke is hide/toggling layers on the map (e.g. just shows geography, no units or base). Again, certainly no ALT+T mod menu loads , CTRL+F4 shows a mod menu that just displays the thinker version.

However in your https://github.com/induktio/thinker/issues/38 @induktio , you provided the "old launcher" the modded terranx_mod.exe. I placed this in the directory and ran it directly and suddenly things worked fine. Also for the first time ever, I see the ALT-T menu in game (neat!).

So there's definitely something up. I can appreciate you going the lengths to reproduce with a VM on Win10 21H2 and not finding the issue, but as someone who is also on W10 21H2 (v.19044.2006) to update on patches, and a clean install of game from GoG-galaxy, and then install of Thinker 3.1 and running from thinker.exe -- there is definitely something not quite right.

**Comment by induktio** [comment]
In the base game, T key stroke is used to toggle terrain layers in map view. When Thinker is running, it intercepts this key when pressed in conjunction with ALT+T to display the mod menu. Otherwise the normal terrain toggling functionality is used. For the feature to work, Thinker must be included in the window event handling process.

It's strange you encountered the issue with same Windows version too. It would lead me to believe it's something to do with Windows settings (maybe antivirus/security settings) that is interfering with the game startup. We could still confirm if this issue happens with all shortcut keys or just this one when using the launcher. If you set smooth_scrolling=1 you should be able to try if this other shortcut ALT+R works in map view or nothing happens? There isn't any other Thinker-added shortcuts in the default build.

`Alt-R   Toggle tile information update under cursor if smooth_scrolling is enabled.`
