### ISSUE TITLE
[Thinker 3.2/3.3] With PracX unable to go windowed mode

### ISSUE THREAD

**Issue by TruthNZ** [induktio/thinker#45]
With both Thinker 3.0, and 3.1 I was able to use PracX to go Windowed mode.
Since updating to Thinker 3.3 I was no longer able to. Confirmed I cannot run it in Thinker 3.2 either.

Process to repeat:
1. Fresh install SMACX.
2. Apply PracX v1.11
3. Install Thinker
4. Start via thinker.exe
5. Pres Alt-Enter to switch to Windowed Mode
(order of 2/3 doesn't seem to matter)

**Comment by induktio** [comment]
Are you running this game with DirectDraw=0 (desktop resolution) or something else? Does alt-tabbing work? Did you try the sdbinst fix in troubleshooting?

**Comment by TruthNZ** [comment]
DirectDraw=0 yes.
Alt-tab works fine.

I'll try the sdbinst fix tomorrow, and update if it works or not.

**Comment by TruthNZ** [comment]
Ok, so my version of this doesn't come with game.sdb or game_add.sdb so I can't run those commands.
I've got an original, install from CD version. (which I am updating through scient v2.1 patch - before applying pracx)

However, as said, Thinker 3.0/3.1 work with alt-tab, whereas 3.2/3.2 don't - nothing else changed about the way I install.

**Comment by induktio** [comment]
It must noted the alt+enter functionality is not part of the vanilla game. It's provided by PRACX which does it by rescaling the current resolution for a smaller window, so items appear smaller. It might have some issues with rendering speed since it uses some bitmap scaling functions for it. You might be able to enter windowed mode from PRACX menu while in game. I'm not sure now what might be causing the keyboard shortcut to not work, maybe if someone submits a patch it could be fixed. If I were to reimplement this kind of windowed mode functionality in Thinker, I would not be using this same method because of the issues with rendering speed. Currently Thinker's own windowed mode does not support resizing the window so it has some limitations.

**Comment by induktio** [comment]
This issue should now be fixed in the latest build so it's possible to use Alt+Enter and other shortcuts with Pracx too. Thinker's mod menu shortcut changes to Alt+H if Pracx is active at the same time. It might still need some more testing on other configurations in case there's anything Windows dependent.
