### ISSUE TITLE
Randomly unable to infiltrate opponents 

### ISSUE THREAD

**Issue by ByrelMitchell** [induktio/thinker#46]
I've had this issue in several games vs. opponents where the infiltration has expired. The option to Infiltrate Datalinks simply doesn't show up. In the save I'm attaching, I'm trying to reinfiltrate Lal. My last infiltration expired several turns ago, but I haven't had the option to infiltrate in several probe actions since then.

Lal does have Hunter-Seeker, but I don't think that's relevant because A) my probe teams all have algorithmic enhancement and B) I've had this issue in previous games versus opponents without Hunter-Seeker.

[Morgan of the Morganites, 2312.zip](https://github.com/induktio/thinker/files/10679039/Morgan.of.the.Morganites.2312.zip)

**Comment by induktio** [comment]
Thanks for the bug reports. Looks like there's some kind of issue with expiring infiltration. In the save game it just looks like the issue happens only with the Peacekeepers and they seem to have the Hunter Seeker project. I'm not sure yet what exactly causes the bug but it might be related to that project. Have to investigate it in detail later. If you have a save of the bug occurring without Hunter Seeker project, that might be helpful. The other issue with the base name labels is much easier to fix since it's just a small oversight because the code doesn't take into account delayed drone riots mechanic.

**Comment by ByrelMitchell** [comment]
I'll get another save next time I see it happen. It also happened with the Believer's later in that same game, so I'm confident it's not related to HS.

Later on in that game, Lal successfully conquered one of my bases, and when I sent a probe team there I was finally able to renew infiltration. That seems like it might narrow down the issue?

**Comment by Michael2589** [comment]
The Believers can get +3 Probe (and often do, they get it whenever they run Fundamentalist), and it's possible that the Hunter Seeker Algorithm shares some code with the effects of a +3 Probe social engineering (since that makes bases immune to some probe team actions).

**Comment by induktio** [comment]
Okay, this bug and #47 should now be fixed in develop build 20230211 and it's available from downloads. When reloading the same savegame, you should now see the option to infiltrate Peacekeepers. Let me know if there are any other issues.
