### ISSUE TITLE
TECHSHARE doesn't work on SMAC-in-SMAX

### ISSUE THREAD

**Issue by Mjnd** [induktio/thinker#57]
The issue has been already discussed on https://old.reddit.com/r/alphacentauri/comments/15sx90w/techshare_doesnt_appear_to_work/

 I understand I'm misusing the SMAC-in-SMAX mod by making use of expansion-related content, but I would like to ask anyway if it would be possible to fix the issue with TECHSHARE as descrived above in the reddit thread, where in SMAC-in-SMAX it behaves like SHARETECH (or is simply ignored), restoring the infiltration requirement for gaining techs.

In general, would be possible to have all the expansion-related rules for factions fully enabled also on SMAC-in-SMAX?

**Comment by induktio** [comment]
As I mentioned on the thread, there's some kind of known issue with SHARETECH and TECHSHARE modifiers such that the vanilla game does not operate like the descriptions in alphax.txt should imply. Can you clarify which description (original/thinker docs) did you use for these features and what would be the better choice for game design?

Regarding the latter question, I did not specifically check this, but the game binary should parse many of the expansion related rules for factions regardless if ExpansionEnabled flag is set or not. The SMAC-in-SMAX mod feature is not absolute since many of these feature flags are checked by the game binary and they're not necessarily 100% consistent regarding the original game. I would have to look at these rules one by one to get an accurate idea how the game binary handles them when ExpansionEnabled  is set to disabled. Are there any specific issues?

**Comment by induktio** [comment]
It seems that capture_base calls steal_tech function when either or both or these conditions are met:

a) Scenario has RULES_SPOILS_OF_WAR enabled
b) Faction definition has RFLAG_TECHSTEAL enabled

There does not seem to be any checking for ExpansionEnabled flag in those functions, so TECHSTEAL feature should work regardless. The only thing that could maybe prevent it from working is if the faction flag does not get parsed properly, but I did not check for this. It's possible to verify it by just starting a new game with the those parameters, whether scenario editor is used should not matter.

**Comment by induktio** [comment]
The game might still parse those rules even if smac_only mode is activated, thus affecting game mechanics unless these instances in the binary are specifically patched out which might be non-trivial. Currently I'd say using expansion factions with smac_only mode is untested (maybe works, report here if you find something that clearly does not). Only alien factions are explicitly unsupported in smac_only mode and using them would not make sense anyway.

**Comment by induktio** [comment]
It seems there's one check in tech_achieved function for ExpansionEnabled flag, so it's probably related to the TECHSHARE issue. If expansion is disabled, the condition always evaluates to true and skips the checks for infiltration, pact, governor and Empath Guild before deciding whether to grant the tech. Not sure what purpose this behavior really serves in the game, so the check for expansion being disabled could maybe be removed.

**Comment by Mjnd** [comment]
I guess it was a way to disable that rule and to avoid problems if it was accidentally added to the original game... Yes, please remove that check when you can... In the meantime I'm glad to know the issue has been solved. Thank you very much! I think this can be closed.

**Comment by Mjnd** [comment]
Could you provide a test/develop build where the changes related to `TECHSHARE` are implemented?
I would like to test and play with `TECHSHARE` fixed... have you time to program a provisional Thinker build?

**Comment by induktio** [comment]
Yeah got a little carried away by other things. Develop build 20230902 should now fix the techshare issue with smac_only. There's also some other tweaks to prototype naming when the new unit name generator is used.

**Comment by Mjnd** [comment]
Thank you very much.
I just tried a game, and it appears to work (and there is non more continous tech gaining at the beginning).
