### ISSUE TITLE
Feature request: Add visual emphasis of bases with a golden age

### ISSUE THREAD

**Issue by pianoslum** [induktio/thinker#6]
As you already added highlighting for HQ...

Afaik the only way to see if a base has a golden age (after the initial pop-up) is in the base menu (F3).
I suggest to add a visual clue when you a) open the base screen or even b) from the world map.

**Comment by induktio** [comment]
That's an interesting idea and could be done quite easily in the world map.

For example, world map could show an yellow(?) outline next to the golden age bases owned by the player. I would not apply that effect to other factions unless infiltration is active. Maybe not even then because it's not that important information for infiltration. Do you have any ideas how this could also be shown in the base screen?

**Comment by pianoslum** [comment]
Yellow outline is a good idea. To be consistent with the drone riot visualization, one could also display a floating "Talent" next to the base.
I guess this could also be visible inside the base in the resource screen.

No that I think of it - is a drone riot highlighted inside the base somehow?

An easy solution could be to use a red font for base name in case of drone riot, a green one during golden age and a white one otherwise?

**Comment by induktio** [comment]
I would not change the font color because for visual clarity, it should be consistent with the faction colors. Maybe just adding a colored outline for population label would be enough. Have to think about it in the next update. I uploaded a new develop build with options for unit repair rates though.

**Comment by pianoslum** [comment]
The more I think of it, the more I like the solution to display a floating talent "head" next to the base. A highlight inside the base would be secondary to me (as it's missing for the drone riot as well)

**Comment by induktio** [comment]
It looks like very problematic to add another icon on that pcx file, not to mention patching the binary to handle reading it correctly. The label is drawn in base_draw function in any case. Unless somebody else contributes the code, I'm not going to patch it further.

Instead I modified the label drawing function to add a yellow label whenever the base is in golden age. It works in the same way than the HQ labels. If you pull the latest commit and compile it, you should see those labels on the world map whenever a base is in golden age. How does that look?

**Comment by pianoslum** [comment]
Works great, thanks :)
