### ISSUE TITLE
Fix Mind Control issue when capturing bases that have non-allied units owned by a third faction inside them.

### ISSUE THREAD

**Issue by tnevolin** [induktio/thinker#71]
Cannot find where is this in the code. 4.3.

I see this:
`write_call(0x5A4AB0, (int)mod_capture_base); // probe`

But the `mod_capture_base` function has nothing in it regarding third party vehicles in it.

**Comment by induktio** [comment]
It is located in that function since the code specifically checks for non-pact units inside the mind controlled base tile, and if any are found, they are deleted. If you have some questions regarding the code documentation, I would recommend putting them on discussions. Issues are meant for gameplay related problems.

**Comment by tnevolin** [comment]
Sure thing. Will go there.
