### ISSUE TITLE
Foil Probe Teams Disappear

### ISSUE THREAD

**Issue by Lyserius** [induktio/thinker#75]
Whenever I automate a Foil Probe Team, it moves and then immediately disappears.

**Comment by induktio** [comment]
Tried this on another map and it didn't seem to be happening, Foil Probe just moved out of the base. What else might be causing this? To be clear the combat unit automation for player factions is only handled by the default AI and it may not be that good generally. In principle Thinker could also automate player combat units but it is not implemented at the moment.

**Comment by induktio** [comment]
Okay I can see it happening now, but maybe not always when the foil probe is automated using Alt+A. This might happen because the original movement code was not developed for foil probes so it just disbands the unit after attempting movement based on some conditions. The simplest workaround for this is just not to automate probe teams. Anyway deciding what probe actions to take is also very important for the faction. The player automation for combat units/probes might be replaced at some point but haven't decided anything about it yet.
