### ISSUE TITLE
[Bug] Invisible unit

### ISSUE THREAD

**Issue by pianoslum** [induktio/thinker#8]
In the attached savegame move the active jet to the south-east, there's a university unit that remains completely invisible.
[InvisibleUnitSE.zip](https://github.com/induktio/thinker/files/5974782/InvisibleUnitSE.zip)

**Comment by induktio** [comment]
I think all three of these bug reports are caused by the same issue. There's a savegame corruption bug caused by design_units feature which creates serious issues with these AI faction prototypes.

Luckily the savegame is salvageable because the corrupted prototypes can be pruned by a patch. If you download the newest develop build, the game should remove any invalid prototypes/units after pressing next turn. Let me know if these issues appear again in the game.

**Comment by pianoslum** [comment]
Thx! I'd love to try, but where can I find the latest dev version? Or do I have to compile it myself?

**Comment by DrazharLn** [comment]
They're in the Dropbox folder linked in the readme. You might need to go up
a directory.

**Comment by induktio** [comment]
It could be done either way, just make sure you pull the latest commit.

**Comment by pianoslum** [comment]
Can confirm that it works, thanks :)
Just curious: Is there a way to find out what's the reason behind the bug?
